import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Header from "@/components/header";
import Footer from "@/components/footer";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full md:w-[1600px] mx-auto">
          <Header></Header>
        </div>
        <div className="md:w-[1600px] mx-auto"> {children} </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
